"""multi_tenant_hierarchy

Revision ID: 82a89a7f27e6
Revises: 20260521_0001
Create Date: 2026-05-27 17:45:09.063388
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql


revision: str = '82a89a7f27e6'
down_revision: Union[str, None] = '20260521_0001'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('organization_types',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('name', sa.String(length=120), nullable=False),
    sa.Column('code', sa.String(length=64), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_organization_types_code'), 'organization_types', ['code'], unique=True)
    op.create_table('permissions',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('name', sa.String(length=120), nullable=False),
    sa.Column('code', sa.String(length=120), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_permissions_code'), 'permissions', ['code'], unique=True)
    op.create_table('roles',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('name', sa.String(length=120), nullable=False),
    sa.Column('code', sa.String(length=64), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_roles_code'), 'roles', ['code'], unique=True)
    op.create_table('branches',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('organization_id', sa.String(length=36), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('location', sa.String(length=255), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_branches_name'), 'branches', ['name'], unique=False)
    op.create_index(op.f('ix_branches_organization_id'), 'branches', ['organization_id'], unique=False)
    op.create_table('departments',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('organization_id', sa.String(length=36), nullable=False),
    sa.Column('name', sa.String(length=120), nullable=False),
    sa.Column('code', sa.String(length=64), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_departments_organization_id'), 'departments', ['organization_id'], unique=False)
    op.create_table('pipelines',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('organization_id', sa.String(length=36), nullable=False),
    sa.Column('name', sa.String(length=120), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_pipelines_is_active'), 'pipelines', ['is_active'], unique=False)
    op.create_index(op.f('ix_pipelines_organization_id'), 'pipelines', ['organization_id'], unique=False)
    op.create_table('pipeline_stages',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('pipeline_id', sa.String(length=36), nullable=False),
    sa.Column('name', sa.String(length=120), nullable=False),
    sa.Column('position', sa.Integer(), nullable=False),
    sa.Column('is_closed', sa.Boolean(), nullable=False),
    sa.Column('probability_percent', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['pipeline_id'], ['pipelines.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_pipeline_stages_pipeline_id'), 'pipeline_stages', ['pipeline_id'], unique=False)
    op.create_index(op.f('ix_pipeline_stages_position'), 'pipeline_stages', ['position'], unique=False)
    op.create_table('users',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('organization_id', sa.String(length=36), nullable=True),
    sa.Column('branch_id', sa.String(length=36), nullable=True),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=True),
    sa.Column('role_id', sa.String(length=36), nullable=False),
    sa.Column('reports_to_id', sa.String(length=36), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['branch_id'], ['branches.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['reports_to_id'], ['users.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['role_id'], ['roles.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_branch_id'), 'users', ['branch_id'], unique=False)
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=False)
    op.create_index(op.f('ix_users_organization_id'), 'users', ['organization_id'], unique=False)
    op.create_index(op.f('ix_users_reports_to_id'), 'users', ['reports_to_id'], unique=False)
    op.create_index(op.f('ix_users_role_id'), 'users', ['role_id'], unique=False)
    op.create_table('assignments',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('organization_id', sa.String(length=36), nullable=False),
    sa.Column('lead_id', sa.String(length=36), nullable=True),
    sa.Column('customer_id', sa.String(length=36), nullable=True),
    sa.Column('user_id', sa.String(length=36), nullable=False),
    sa.Column('assigned_by_id', sa.String(length=36), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['assigned_by_id'], ['users.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['customer_id'], ['customers.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['lead_id'], ['leads.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_assignments_customer_id'), 'assignments', ['customer_id'], unique=False)
    op.create_index(op.f('ix_assignments_lead_id'), 'assignments', ['lead_id'], unique=False)
    op.create_index(op.f('ix_assignments_organization_id'), 'assignments', ['organization_id'], unique=False)
    op.create_index(op.f('ix_assignments_user_id'), 'assignments', ['user_id'], unique=False)
    op.create_table('communication_logs',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('organization_id', sa.String(length=36), nullable=False),
    sa.Column('lead_id', sa.String(length=36), nullable=True),
    sa.Column('customer_id', sa.String(length=36), nullable=True),
    sa.Column('type', sa.String(length=64), nullable=False),
    sa.Column('direction', sa.String(length=32), nullable=False),
    sa.Column('content', sa.Text(), nullable=True),
    sa.Column('logged_by_id', sa.String(length=36), nullable=True),
    sa.Column('status', sa.String(length=64), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['customer_id'], ['customers.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['lead_id'], ['leads.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['logged_by_id'], ['users.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_communication_logs_customer_id'), 'communication_logs', ['customer_id'], unique=False)
    op.create_index(op.f('ix_communication_logs_direction'), 'communication_logs', ['direction'], unique=False)
    op.create_index(op.f('ix_communication_logs_lead_id'), 'communication_logs', ['lead_id'], unique=False)
    op.create_index(op.f('ix_communication_logs_organization_id'), 'communication_logs', ['organization_id'], unique=False)
    op.create_index(op.f('ix_communication_logs_type'), 'communication_logs', ['type'], unique=False)
    op.create_table('documents',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('organization_id', sa.String(length=36), nullable=False),
    sa.Column('lead_id', sa.String(length=36), nullable=True),
    sa.Column('customer_id', sa.String(length=36), nullable=True),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('file_type', sa.String(length=64), nullable=False),
    sa.Column('file_url', sa.Text(), nullable=False),
    sa.Column('uploaded_by_id', sa.String(length=36), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['customer_id'], ['customers.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['lead_id'], ['leads.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_documents_customer_id'), 'documents', ['customer_id'], unique=False)
    op.create_index(op.f('ix_documents_file_type'), 'documents', ['file_type'], unique=False)
    op.create_index(op.f('ix_documents_lead_id'), 'documents', ['lead_id'], unique=False)
    op.create_index(op.f('ix_documents_organization_id'), 'documents', ['organization_id'], unique=False)
    op.add_column('contacts', sa.Column('organization_id', sa.String(length=36), nullable=True))
    op.add_column('contacts', sa.Column('branch_id', sa.String(length=36), nullable=True))
    op.create_index(op.f('ix_contacts_branch_id'), 'contacts', ['branch_id'], unique=False)
    op.create_index(op.f('ix_contacts_organization_id'), 'contacts', ['organization_id'], unique=False)
    op.create_foreign_key(None, 'contacts', 'organizations', ['organization_id'], ['id'], ondelete='SET NULL')
    op.create_foreign_key(None, 'contacts', 'branches', ['branch_id'], ['id'], ondelete='SET NULL')
    op.add_column('conversations', sa.Column('organization_id', sa.String(length=36), nullable=True))
    op.add_column('conversations', sa.Column('branch_id', sa.String(length=36), nullable=True))
    op.create_index(op.f('ix_conversations_assigned_user_id'), 'conversations', ['assigned_user_id'], unique=False)
    op.create_index(op.f('ix_conversations_branch_id'), 'conversations', ['branch_id'], unique=False)
    op.create_index(op.f('ix_conversations_organization_id'), 'conversations', ['organization_id'], unique=False)
    op.create_foreign_key(None, 'conversations', 'branches', ['branch_id'], ['id'], ondelete='SET NULL')
    op.create_foreign_key(None, 'conversations', 'organizations', ['organization_id'], ['id'], ondelete='SET NULL')
    op.add_column('customers', sa.Column('organization_id', sa.String(length=36), nullable=True))
    op.add_column('customers', sa.Column('branch_id', sa.String(length=36), nullable=True))
    op.add_column('customers', sa.Column('password_hash', sa.String(length=255), nullable=True))
    op.drop_index('ix_customers_type', table_name='customers')
    op.create_index(op.f('ix_customers_branch_id'), 'customers', ['branch_id'], unique=False)
    op.create_index(op.f('ix_customers_organization_id'), 'customers', ['organization_id'], unique=False)
    op.create_foreign_key(None, 'customers', 'branches', ['branch_id'], ['id'], ondelete='SET NULL')
    op.create_foreign_key(None, 'customers', 'organizations', ['organization_id'], ['id'], ondelete='SET NULL')
    op.drop_column('customers', 'last_contact_date')
    op.drop_column('customers', 'type')
    op.drop_column('customers', 'score')
    op.add_column('inboxes', sa.Column('organization_id', sa.String(length=36), nullable=True))
    op.add_column('inboxes', sa.Column('branch_id', sa.String(length=36), nullable=True))
    op.create_index(op.f('ix_inboxes_branch_id'), 'inboxes', ['branch_id'], unique=False)
    op.create_index(op.f('ix_inboxes_organization_id'), 'inboxes', ['organization_id'], unique=False)
    op.create_foreign_key(None, 'inboxes', 'organizations', ['organization_id'], ['id'], ondelete='SET NULL')
    op.create_foreign_key(None, 'inboxes', 'branches', ['branch_id'], ['id'], ondelete='SET NULL')
    op.add_column('lead_activities', sa.Column('organization_id', sa.String(length=36), nullable=True))
    op.add_column('lead_activities', sa.Column('branch_id', sa.String(length=36), nullable=True))
    op.create_index(op.f('ix_lead_activities_branch_id'), 'lead_activities', ['branch_id'], unique=False)
    op.create_index(op.f('ix_lead_activities_organization_id'), 'lead_activities', ['organization_id'], unique=False)
    op.create_foreign_key(None, 'lead_activities', 'branches', ['branch_id'], ['id'], ondelete='SET NULL')
    op.create_foreign_key(None, 'lead_activities', 'organizations', ['organization_id'], ['id'], ondelete='SET NULL')
    op.drop_constraint('lead_areas_name_key', 'lead_areas', type_='unique')
    op.drop_index('ix_lead_areas_name', table_name='lead_areas')
    op.create_index(op.f('ix_lead_areas_name'), 'lead_areas', ['name'], unique=True)
    op.drop_constraint('lead_professions_name_key', 'lead_professions', type_='unique')
    op.drop_index('ix_lead_professions_name', table_name='lead_professions')
    op.create_index(op.f('ix_lead_professions_name'), 'lead_professions', ['name'], unique=True)
    op.drop_constraint('lead_sectors_name_key', 'lead_sectors', type_='unique')
    op.drop_index('ix_lead_sectors_name', table_name='lead_sectors')
    op.create_index(op.f('ix_lead_sectors_name'), 'lead_sectors', ['name'], unique=True)
    op.drop_constraint('lead_sources_name_key', 'lead_sources', type_='unique')
    op.drop_index('ix_lead_sources_name', table_name='lead_sources')
    op.create_index(op.f('ix_lead_sources_name'), 'lead_sources', ['name'], unique=True)
    op.drop_constraint('lead_stages_name_key', 'lead_stages', type_='unique')
    op.drop_index('ix_lead_stages_name', table_name='lead_stages')
    op.create_index(op.f('ix_lead_stages_name'), 'lead_stages', ['name'], unique=True)
    op.add_column('leads', sa.Column('organization_id', sa.String(length=36), nullable=True))
    op.add_column('leads', sa.Column('branch_id', sa.String(length=36), nullable=True))
    op.add_column('leads', sa.Column('department_id', sa.String(length=36), nullable=True))
    op.add_column('leads', sa.Column('last_education', sa.String(length=255), nullable=True))
    op.alter_column('leads', 'industry_data',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               comment=None,
               existing_comment='Dynamic industry-specific fields. Schema varies by industry:\r\n   real_estate  → company_name text, budget numeric, square_feet numeric\r\n   study_abroad → preferred_country enum(UK|US|AUS|CA), financial_status text\r\n   ecommerce    → product_interest text, delivery_location text,\r\n                  urgency_level text(Low|Medium|High),\r\n                  preferred_platform text(Messenger|WhatsApp)',
               existing_nullable=True)
    op.alter_column('leads', 'raw_note',
               existing_type=sa.TEXT(),
               comment=None,
               existing_comment='Original raw agent note. Preserved verbatim for auditing purposes.',
               existing_nullable=True)
    op.alter_column('leads', 'agent_id',
               existing_type=sa.TEXT(),
               type_=sa.String(length=36),
               comment=None,
               existing_comment='UUID of the Supabase auth user (agent) who submitted/owns this lead.',
               existing_nullable=True)
    op.drop_index('idx_leads_agent_id', table_name='leads')
    op.drop_index('idx_leads_industry_data', table_name='leads', postgresql_using='gin')
    op.create_index(op.f('ix_leads_agent_id'), 'leads', ['agent_id'], unique=False)
    op.create_index(op.f('ix_leads_branch_id'), 'leads', ['branch_id'], unique=False)
    op.create_index(op.f('ix_leads_department_id'), 'leads', ['department_id'], unique=False)
    op.create_index(op.f('ix_leads_organization_id'), 'leads', ['organization_id'], unique=False)
    op.drop_constraint('leads_org_id_fkey', 'leads', type_='foreignkey')
    op.create_foreign_key(None, 'leads', 'organizations', ['organization_id'], ['id'], ondelete='SET NULL')
    op.create_foreign_key(None, 'leads', 'departments', ['department_id'], ['id'], ondelete='SET NULL')
    op.create_foreign_key(None, 'leads', 'branches', ['branch_id'], ['id'], ondelete='SET NULL')
    op.drop_column('leads', 'org_id')
    op.add_column('messages', sa.Column('organization_id', sa.String(length=36), nullable=True))
    op.add_column('messages', sa.Column('branch_id', sa.String(length=36), nullable=True))
    op.create_index(op.f('ix_messages_branch_id'), 'messages', ['branch_id'], unique=False)
    op.create_index(op.f('ix_messages_organization_id'), 'messages', ['organization_id'], unique=False)
    op.create_foreign_key(None, 'messages', 'branches', ['branch_id'], ['id'], ondelete='SET NULL')
    op.create_foreign_key(None, 'messages', 'organizations', ['organization_id'], ['id'], ondelete='SET NULL')
    op.add_column('opportunities', sa.Column('organization_id', sa.String(length=36), nullable=True))
    op.add_column('opportunities', sa.Column('branch_id', sa.String(length=36), nullable=True))
    op.create_index(op.f('ix_opportunities_branch_id'), 'opportunities', ['branch_id'], unique=False)
    op.create_index(op.f('ix_opportunities_organization_id'), 'opportunities', ['organization_id'], unique=False)
    op.create_foreign_key(None, 'opportunities', 'organizations', ['organization_id'], ['id'], ondelete='SET NULL')
    op.create_foreign_key(None, 'opportunities', 'branches', ['branch_id'], ['id'], ondelete='SET NULL')
    op.add_column('orders', sa.Column('organization_id', sa.String(length=36), nullable=True))
    op.add_column('orders', sa.Column('branch_id', sa.String(length=36), nullable=True))
    op.create_index(op.f('ix_orders_branch_id'), 'orders', ['branch_id'], unique=False)
    op.create_index(op.f('ix_orders_organization_id'), 'orders', ['organization_id'], unique=False)
    op.create_foreign_key(None, 'orders', 'organizations', ['organization_id'], ['id'], ondelete='SET NULL')
    op.create_foreign_key(None, 'orders', 'branches', ['branch_id'], ['id'], ondelete='SET NULL')
    op.add_column('organizations', sa.Column('allow_public_shares', sa.Boolean(), server_default=sa.text('true'), nullable=False))
    op.add_column('organizations', sa.Column('default_share_expiry_days', sa.Integer(), nullable=True))
    op.add_column('organizations', sa.Column('organization_type_id', sa.String(length=36), nullable=True))
    op.alter_column('organizations', 'company_name',
               existing_type=sa.TEXT(),
               type_=sa.String(length=255),
               existing_nullable=False)
    op.alter_column('organizations', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=False,
               existing_server_default=sa.text('now()'))
    op.alter_column('organizations', 'updated_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=False,
               existing_server_default=sa.text('now()'))
    op.drop_index('idx_organizations_id', table_name='organizations')
    op.create_index(op.f('ix_organizations_company_name'), 'organizations', ['company_name'], unique=False)
    op.create_index(op.f('ix_organizations_organization_type_id'), 'organizations', ['organization_type_id'], unique=False)
    op.create_foreign_key(None, 'organizations', 'organization_types', ['organization_type_id'], ['id'], ondelete='SET NULL')
    op.drop_column('organizations', 'encrypted_ai_key')
    op.drop_column('organizations', 'ai_provider')
    op.add_column('tasks', sa.Column('organization_id', sa.String(length=36), nullable=True))
    op.add_column('tasks', sa.Column('branch_id', sa.String(length=36), nullable=True))
    op.alter_column('tasks', 'entity_id',
               existing_type=sa.VARCHAR(length=36),
               nullable=True)
    op.create_index(op.f('ix_tasks_branch_id'), 'tasks', ['branch_id'], unique=False)
    op.create_index(op.f('ix_tasks_organization_id'), 'tasks', ['organization_id'], unique=False)
    op.create_foreign_key(None, 'tasks', 'organizations', ['organization_id'], ['id'], ondelete='SET NULL')
    op.create_foreign_key(None, 'tasks', 'branches', ['branch_id'], ['id'], ondelete='SET NULL')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'tasks', type_='foreignkey')
    op.drop_constraint(None, 'tasks', type_='foreignkey')
    op.drop_index(op.f('ix_tasks_organization_id'), table_name='tasks')
    op.drop_index(op.f('ix_tasks_branch_id'), table_name='tasks')
    op.alter_column('tasks', 'entity_id',
               existing_type=sa.VARCHAR(length=36),
               nullable=False)
    op.drop_column('tasks', 'branch_id')
    op.drop_column('tasks', 'organization_id')
    op.add_column('organizations', sa.Column('ai_provider', sa.TEXT(), server_default=sa.text("'groq'::text"), autoincrement=False, nullable=True))
    op.add_column('organizations', sa.Column('encrypted_ai_key', sa.TEXT(), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'organizations', type_='foreignkey')
    op.drop_index(op.f('ix_organizations_organization_type_id'), table_name='organizations')
    op.drop_index(op.f('ix_organizations_company_name'), table_name='organizations')
    op.create_index('idx_organizations_id', 'organizations', ['id'], unique=False)
    op.alter_column('organizations', 'updated_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=True,
               existing_server_default=sa.text('now()'))
    op.alter_column('organizations', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=True,
               existing_server_default=sa.text('now()'))
    op.alter_column('organizations', 'company_name',
               existing_type=sa.String(length=255),
               type_=sa.TEXT(),
               existing_nullable=False)
    op.drop_column('organizations', 'organization_type_id')
    op.drop_column('organizations', 'default_share_expiry_days')
    op.drop_column('organizations', 'allow_public_shares')
    op.drop_constraint(None, 'orders', type_='foreignkey')
    op.drop_constraint(None, 'orders', type_='foreignkey')
    op.drop_index(op.f('ix_orders_organization_id'), table_name='orders')
    op.drop_index(op.f('ix_orders_branch_id'), table_name='orders')
    op.drop_column('orders', 'branch_id')
    op.drop_column('orders', 'organization_id')
    op.drop_constraint(None, 'opportunities', type_='foreignkey')
    op.drop_constraint(None, 'opportunities', type_='foreignkey')
    op.drop_index(op.f('ix_opportunities_organization_id'), table_name='opportunities')
    op.drop_index(op.f('ix_opportunities_branch_id'), table_name='opportunities')
    op.drop_column('opportunities', 'branch_id')
    op.drop_column('opportunities', 'organization_id')
    op.drop_constraint(None, 'messages', type_='foreignkey')
    op.drop_constraint(None, 'messages', type_='foreignkey')
    op.drop_index(op.f('ix_messages_organization_id'), table_name='messages')
    op.drop_index(op.f('ix_messages_branch_id'), table_name='messages')
    op.drop_column('messages', 'branch_id')
    op.drop_column('messages', 'organization_id')
    op.add_column('leads', sa.Column('org_id', sa.VARCHAR(length=36), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'leads', type_='foreignkey')
    op.drop_constraint(None, 'leads', type_='foreignkey')
    op.drop_constraint(None, 'leads', type_='foreignkey')
    op.create_foreign_key('leads_org_id_fkey', 'leads', 'organizations', ['org_id'], ['id'])
    op.drop_index(op.f('ix_leads_organization_id'), table_name='leads')
    op.drop_index(op.f('ix_leads_department_id'), table_name='leads')
    op.drop_index(op.f('ix_leads_branch_id'), table_name='leads')
    op.drop_index(op.f('ix_leads_agent_id'), table_name='leads')
    op.create_index('idx_leads_industry_data', 'leads', ['industry_data'], unique=False, postgresql_using='gin')
    op.create_index('idx_leads_agent_id', 'leads', ['agent_id'], unique=False)
    op.alter_column('leads', 'agent_id',
               existing_type=sa.String(length=36),
               type_=sa.TEXT(),
               comment='UUID of the Supabase auth user (agent) who submitted/owns this lead.',
               existing_nullable=True)
    op.alter_column('leads', 'raw_note',
               existing_type=sa.TEXT(),
               comment='Original raw agent note. Preserved verbatim for auditing purposes.',
               existing_nullable=True)
    op.alter_column('leads', 'industry_data',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               comment='Dynamic industry-specific fields. Schema varies by industry:\r\n   real_estate  → company_name text, budget numeric, square_feet numeric\r\n   study_abroad → preferred_country enum(UK|US|AUS|CA), financial_status text\r\n   ecommerce    → product_interest text, delivery_location text,\r\n                  urgency_level text(Low|Medium|High),\r\n                  preferred_platform text(Messenger|WhatsApp)',
               existing_nullable=True)
    op.drop_column('leads', 'last_education')
    op.drop_column('leads', 'department_id')
    op.drop_column('leads', 'branch_id')
    op.drop_column('leads', 'organization_id')
    op.drop_index(op.f('ix_lead_stages_name'), table_name='lead_stages')
    op.create_index('ix_lead_stages_name', 'lead_stages', ['name'], unique=False)
    op.create_unique_constraint('lead_stages_name_key', 'lead_stages', ['name'])
    op.drop_index(op.f('ix_lead_sources_name'), table_name='lead_sources')
    op.create_index('ix_lead_sources_name', 'lead_sources', ['name'], unique=False)
    op.create_unique_constraint('lead_sources_name_key', 'lead_sources', ['name'])
    op.drop_index(op.f('ix_lead_sectors_name'), table_name='lead_sectors')
    op.create_index('ix_lead_sectors_name', 'lead_sectors', ['name'], unique=False)
    op.create_unique_constraint('lead_sectors_name_key', 'lead_sectors', ['name'])
    op.drop_index(op.f('ix_lead_professions_name'), table_name='lead_professions')
    op.create_index('ix_lead_professions_name', 'lead_professions', ['name'], unique=False)
    op.create_unique_constraint('lead_professions_name_key', 'lead_professions', ['name'])
    op.drop_index(op.f('ix_lead_areas_name'), table_name='lead_areas')
    op.create_index('ix_lead_areas_name', 'lead_areas', ['name'], unique=False)
    op.create_unique_constraint('lead_areas_name_key', 'lead_areas', ['name'])
    op.drop_constraint(None, 'lead_activities', type_='foreignkey')
    op.drop_constraint(None, 'lead_activities', type_='foreignkey')
    op.drop_index(op.f('ix_lead_activities_organization_id'), table_name='lead_activities')
    op.drop_index(op.f('ix_lead_activities_branch_id'), table_name='lead_activities')
    op.drop_column('lead_activities', 'branch_id')
    op.drop_column('lead_activities', 'organization_id')
    op.drop_constraint(None, 'inboxes', type_='foreignkey')
    op.drop_constraint(None, 'inboxes', type_='foreignkey')
    op.drop_index(op.f('ix_inboxes_organization_id'), table_name='inboxes')
    op.drop_index(op.f('ix_inboxes_branch_id'), table_name='inboxes')
    op.drop_column('inboxes', 'branch_id')
    op.drop_column('inboxes', 'organization_id')
    op.add_column('customers', sa.Column('score', sa.INTEGER(), autoincrement=False, nullable=False))
    op.add_column('customers', sa.Column('type', sa.VARCHAR(length=64), autoincrement=False, nullable=True))
    op.add_column('customers', sa.Column('last_contact_date', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'customers', type_='foreignkey')
    op.drop_constraint(None, 'customers', type_='foreignkey')
    op.drop_index(op.f('ix_customers_organization_id'), table_name='customers')
    op.drop_index(op.f('ix_customers_branch_id'), table_name='customers')
    op.create_index('ix_customers_type', 'customers', ['type'], unique=False)
    op.drop_column('customers', 'password_hash')
    op.drop_column('customers', 'branch_id')
    op.drop_column('customers', 'organization_id')
    op.drop_constraint(None, 'conversations', type_='foreignkey')
    op.drop_constraint(None, 'conversations', type_='foreignkey')
    op.drop_index(op.f('ix_conversations_organization_id'), table_name='conversations')
    op.drop_index(op.f('ix_conversations_branch_id'), table_name='conversations')
    op.drop_index(op.f('ix_conversations_assigned_user_id'), table_name='conversations')
    op.drop_column('conversations', 'branch_id')
    op.drop_column('conversations', 'organization_id')
    op.drop_constraint(None, 'contacts', type_='foreignkey')
    op.drop_constraint(None, 'contacts', type_='foreignkey')
    op.drop_index(op.f('ix_contacts_organization_id'), table_name='contacts')
    op.drop_index(op.f('ix_contacts_branch_id'), table_name='contacts')
    op.drop_column('contacts', 'branch_id')
    op.drop_column('contacts', 'organization_id')
    op.drop_index(op.f('ix_documents_organization_id'), table_name='documents')
    op.drop_index(op.f('ix_documents_lead_id'), table_name='documents')
    op.drop_index(op.f('ix_documents_file_type'), table_name='documents')
    op.drop_index(op.f('ix_documents_customer_id'), table_name='documents')
    op.drop_table('documents')
    op.drop_index(op.f('ix_communication_logs_type'), table_name='communication_logs')
    op.drop_index(op.f('ix_communication_logs_organization_id'), table_name='communication_logs')
    op.drop_index(op.f('ix_communication_logs_lead_id'), table_name='communication_logs')
    op.drop_index(op.f('ix_communication_logs_direction'), table_name='communication_logs')
    op.drop_index(op.f('ix_communication_logs_customer_id'), table_name='communication_logs')
    op.drop_table('communication_logs')
    op.drop_index(op.f('ix_assignments_user_id'), table_name='assignments')
    op.drop_index(op.f('ix_assignments_organization_id'), table_name='assignments')
    op.drop_index(op.f('ix_assignments_lead_id'), table_name='assignments')
    op.drop_index(op.f('ix_assignments_customer_id'), table_name='assignments')
    op.drop_table('assignments')
    op.drop_index(op.f('ix_users_role_id'), table_name='users')
    op.drop_index(op.f('ix_users_reports_to_id'), table_name='users')
    op.drop_index(op.f('ix_users_organization_id'), table_name='users')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_index(op.f('ix_users_branch_id'), table_name='users')
    op.drop_table('users')
    op.drop_index(op.f('ix_pipeline_stages_position'), table_name='pipeline_stages')
    op.drop_index(op.f('ix_pipeline_stages_pipeline_id'), table_name='pipeline_stages')
    op.drop_table('pipeline_stages')
    op.drop_index(op.f('ix_pipelines_organization_id'), table_name='pipelines')
    op.drop_index(op.f('ix_pipelines_is_active'), table_name='pipelines')
    op.drop_table('pipelines')
    op.drop_index(op.f('ix_departments_organization_id'), table_name='departments')
    op.drop_table('departments')
    op.drop_index(op.f('ix_branches_organization_id'), table_name='branches')
    op.drop_index(op.f('ix_branches_name'), table_name='branches')
    op.drop_table('branches')
    op.drop_index(op.f('ix_roles_code'), table_name='roles')
    op.drop_table('roles')
    op.drop_index(op.f('ix_permissions_code'), table_name='permissions')
    op.drop_table('permissions')
    op.drop_index(op.f('ix_organization_types_code'), table_name='organization_types')
    op.drop_table('organization_types')
    # ### end Alembic commands ###
