"""add_lead_sla_fields

Revision ID: e6172ef51a77
Revises: 20260527_0002
Create Date: 2026-06-05 20:19:52.009763
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa



revision: str = 'e6172ef51a77'
down_revision: Union[str, None] = '20260527_0002'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_lead_stages_org_name', table_name='lead_stages')
    op.add_column('leads', sa.Column('assigned_at', sa.DateTime(timezone=True), nullable=True))
    op.add_column('leads', sa.Column('sla_duration_hours', sa.Integer(), nullable=True))
    op.add_column('leads', sa.Column('target_stage_id', sa.String(length=36), nullable=True))
    op.add_column('leads', sa.Column('target_stage_by', sa.DateTime(timezone=True), nullable=True))
    op.create_index(op.f('ix_leads_target_stage_id'), 'leads', ['target_stage_id'], unique=False)
    op.create_foreign_key(None, 'leads', 'lead_stages', ['target_stage_id'], ['id'], ondelete='SET NULL')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'leads', type_='foreignkey')
    op.drop_index(op.f('ix_leads_target_stage_id'), table_name='leads')
    op.drop_column('leads', 'target_stage_by')
    op.drop_column('leads', 'target_stage_id')
    op.drop_column('leads', 'sla_duration_hours')
    op.drop_column('leads', 'assigned_at')
    op.create_index('ix_lead_stages_org_name', 'lead_stages', ['organization_id', 'name'], unique=True)
    # ### end Alembic commands ###
